# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:
frontend:
  themes: !include_dir_merge_named themes

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

influxdb:
  host: a0d7b954-influxdb
  port: 8086
  database: homeassistant
  username: homeassistant
  password: homeassistant
  max_retries: 3
  default_measurement: state

sensor:

  - platform: mqtt
    name: "sensorMaquinaria"
    state_topic: "/iot/e2/power/pub/maquinaria"

  - platform: mqtt
    name: "sensorCafeteria"
    state_topic: "/iot/e2/power/pub/cafeteria"

  - platform: mqtt
    name: "sensorTotal"
    state_topic: "/iot/e2/power/pub"
    
  - platform: time_date
    display_options:
      - 'time'
      - 'date'
      - 'date_time'
      - 'date_time_utc'
      - 'date_time_iso'
      - 'time_date'
      - 'time_utc'
      - 'beat'

switch:

  - platform: mqtt
    name: "Cafeteria"
    #state_topic: "/iot/e2/status/cafeteria"
    command_topic: "/iot/e2/execute/cafeteria"
    payload_on: "1"
    payload_off: "0"

  - platform: mqtt
    name: "Maquinaria"
    #state_topic: "/iot/e2/status/maquinaria"
    command_topic: "/iot/e2/execute/maquinaria"
    payload_on: "1"
    payload_off: "0"
